
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    env:
      SHELL: /bin/bash
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Clean everything and start from scratch
        run: make clean clean-deps

      - name: Install all the dependencies
        run: sudo apt-get install python3-venv && make install-deps

      - name: Build the project
        run: make build -j

      - name: Verify the built files
        run: make verify

      - name: Setup Github config
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Clone the Github pages repository
        run: git clone https://${{ secrets.GH_TOKEN }}@github.com/tanayseven/tanayseven.github.io.git

      - name: Deploy to Github pages
        run: make deploy

      - name: Lighthouse CI
      - uses: actions/checkout@v2

      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v3
        with:
          urls: |
            https://tanayseven.com/
            https://tanayseven.com/blog
          budgetPath: ./budget.json # test performance budgets
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage
