
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
    
      - name: Bash for GitHub Actions
        uses: jcblw/bash@1.0.0
        
      - name: Clean everything and start from scratch
        run: make clean clean-deps

      - name: Install all the dependencies
        run: make build
        
      - name: Verify the built files
        run: make verify
      
      - name: deploy
        run: echo To be updated
